#!/bin/sh
set -e
cgroup_path="$(cut -d : -f 3 /proc/self/cgroup)"
cgroup_brief="$(echo "$cgroup_path" | rev | cut -d / -f 2 | rev | cut -d . -f 1)"
if [ "$(echo "$cgroup_path" | cut -d / -f 2)" = "user.slice" ]; then
	cgroup_brief="${cgroup_brief}u"
fi
echo "$cgroup_brief"
